### ISSUE TITLE
ENOENT: no such file or directory, open '.svelte-kit/cdk/prerendered.ts'

### ISSUE THREAD

**Issue by kipwoker** [juranki/sveltekit-cdk#17]
Hi, I've cloned the project and tried to build [sample-site-v2](https://github.com/juranki/sveltekit-cdk/tree/main/packages/sample-site-v2) locally but got an error.

```
PS C:\Projects\sveltekit-cdk\packages\sample-site-v2> npm run build

> sample-site-v2@0.0.1 build
> svelte-kit build

vite v2.8.4 building for production...
✓ 34 modules transformed.
.svelte-kit/output/client/_app/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/_app/manifest.json                                             2.51 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-bebcd6f4.js                         4.76 KiB / gzip: 1.86 KiB
.svelte-kit/output/client/_app/error.svelte-03fd07aa.js                                  1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/index.svelte-1ae8d99e.js                            4.09 KiB / gzip: 1.69 KiB
.svelte-kit/output/client/_app/pages/about.svelte-6a2313b8.js                            2.40 KiB / gzip: 1.10 KiB
.svelte-kit/output/client/_app/start-84be8230.js                                         24.21 KiB / gzip: 8.25 KiB
.svelte-kit/output/client/_app/chunks/singletons-a6a7384f.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/pages/todos/index.svelte-8df487bb.js                      5.91 KiB / gzip: 2.40 KiB
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-15681802.css                 4.96 KiB / gzip: 1.55 KiB
.svelte-kit/output/client/_app/chunks/vendor-ee294e9e.js                                 14.16 KiB / gzip: 6.04 KiB
.svelte-kit/output/client/_app/assets/pages/about.svelte-bf4528fa.css                    0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/assets/pages/todos/index.svelte-784042c1.css              3.70 KiB / gzip: 1.04 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-1d45bd0c.css                    1.40 KiB / gzip: 0.50 KiB
vite v2.8.4 building SSR bundle for production...
✓ 36 modules transformed.
.svelte-kit/output/server/manifest.json                         2.15 KiB
.svelte-kit/output/server/app.js                                64.64 KiB
.svelte-kit/output/server/entries/endpoints/todos/index.ts.js   1.23 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js      4.60 KiB
.svelte-kit/output/server/entries/pages/error.svelte.js         0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js         8.07 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js         1.30 KiB
.svelte-kit/output/server/entries/pages/todos/index.svelte.js   5.84 KiB
.svelte-kit/output/server/chunks/index-ee9fdf1a.js              4.24 KiB

Run npm run preview to preview your production build locally.

> Using sveltekit-cdk-adapter
> ENOENT: no such file or directory, open '.svelte-kit/cdk/prerendered.ts'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2155:35)
    at writePrerenderedTs (file:///C:/Projects/sveltekit-cdk/packages/sample-site-v2/node_modules/@sveltekit-cdk/adapter/dist/index.js:88:5)
    at file:///C:/Projects/sveltekit-cdk/packages/sample-site-v2/node_modules/@sveltekit-cdk/adapter/dist/index.js:51:17
    at Generator.next (<anonymous>)
    at fulfilled (file:///C:/Projects/sveltekit-cdk/packages/sample-site-v2/node_modules/@sveltekit-cdk/adapter/dist/index.js:4:58)
PS C:\Projects\sveltekit-cdk\packages\sample-site-v2> 
```

**Environment**
OS: Win10 Pro 19043.1526
Node: v16.14.0
npm: v8.5.1

My steps were like:
1. I tried to run `npm install`. But got an error about can't recognize the workspace.
2. So I decided to take the latest version and ran `npm install @sveltekit-cdk/adapter@latest --dev`
3. Version was substituted with `^0.7.2` and I ran `npm run build`. After that, I've got the log above

So, my assumption maybe there is an issue with Windows and it works on macOS/Linux only, but I can't check it at the moment. But maybe that's a wrong assumption. Do you have any ideas how I can fix that? :)

**Comment by juranki** [comment]
This project is using [pnpm](https://pnpm.io) instead of npm. Then workspace error could be about that.
I suggest trying pnpm first.

**Comment by kipwoker** [comment]
Thanks, `pnpm` works for the workspace. 
But `pnpm run build` still respond with `ENOENT: no such file or directory, open '.svelte-kit/cdk/prerendered.ts'`

**Comment by juranki** [comment]
Yes, it's a bug. [Here](https://github.com/juranki/sveltekit-cdk/blob/main/packages/adapter/src/index.ts#L86).
Must use `path.join` to construct the path.

Thanks!!

I'll fix it tomorrow evening.

**Comment by juranki** [comment]
I'm afraid there's more that just one path. I'll have to find a windows machine before I can examine the differences more closely.
